services:
  postgres:
    image: postgres:15-alpine
    container_name: fly-visa-db
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d crm_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: fly-visa-backend
    ports:
      - "3001:3001"
    # Nạp biến từ file .env (Để GCS_BUCKET_NAME, GCS_PROJECT_ID...)
    env_file:
      - ./backend/.env
    environment:
      # Kết nối nội bộ giữa các container
      DATABASE_URL: "postgresql://admin:admin123@postgres:5432/crm_db?schema=public"
      NODE_ENV: development
      PORT: 3001
    volumes:
      - ./backend/uploads:/app/uploads
      # [QUAN TRỌNG] Mount thư mục config để code đọc file google-key.json ở local
      - ./backend/config:/app/config
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules/
            - uploads/
            - config/
        - action: rebuild
          path: ./backend/package.json

  frontend:
    build:
      context: ./front-end
      dockerfile: dockerfile.dev
    container_name: fly-visa-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:3001"
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./front-end
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./front-end/package.json

volumes:
  pgdata: